# Generated by Django 2.2.28 on 2024-03-14 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenrr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='contact_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
