# Generated by Django 2.2.28 on 2024-03-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenrr', '0008_auto_20240318_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
