# Generated by Django 2.2.28 on 2024-03-19 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenrr', '0010_sale_salemedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='purchase_media/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='tenrr.Purchase')),
            ],
        ),
    ]
