# Generated by Django 2.2.28 on 2024-03-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenrr', '0011_purchasemedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salemedia',
            name='sale',
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
        migrations.DeleteModel(
            name='SaleMedia',
        ),
    ]
