# Generated by Django 2.2.28 on 2024-03-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenrr', '0012_auto_20240319_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
